__title__ = 'videodl-youku'
__description__ = 'Youku-only video downloader optimized for Android Termux'
__url__ = 'https://github.com/505260991/videodl'
__version__ = '0.9.1-youku'
__author__ = '505260991'
__license__ = 'PolyForm-Noncommercial-1.0.0'
